---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: getourneau/alpine-bash-git
inputs:
  - name: repo
  - name: repo-release
outputs:
  - name: out
run:
  path: /bin/bash
  args:
  - repo-release/ci/tasks/merge-release-branch.sh